# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_loss_cpp <- function(x, y, w, c0, lambda) {
    .Call(`_riskslimr_cplex_test_loss_cpp`, x, y, w, c0, lambda)
}

test_loss_grad_cpp <- function(x, y, w, c0, lambda) {
    .Call(`_riskslimr_cplex_test_loss_grad_cpp`, x, y, w, c0, lambda)
}

lcpa_cpp <- function(x, y, weights, logfile, R_max = 3L, time_limit = 60L) {
    .Call(`_riskslimr_cplex_lcpa_cpp`, x, y, weights, logfile, R_max, time_limit)
}

